import type { Metadata } from "next";
import "./globals.css";
import { Archivo } from 'next/font/google'
import AuthProvider from "@/context/AuthProvider";

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={archivo.className}>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
